---
- hosts: localhost
  gather_facts: false
  connection: local
  become: yes

  tasks:
  - name: Install microk8s
    become: yes
    snap:
      name: microk8s
      classic: yes
  - name: Enable services
    shell: microk8s enable dashboard dns
  - name: Helm start
    kubernetes.core.helm:
      release_name: "jenkins"
      release_namespace: "jenkins"
      create_namespace: yes
      chart_repo_url: "https://danielkhan-v1.github.io/lab-k8s/"