---
- hosts: localhost
  gather_facts: false
  connection: local
  become: yes

  tasks:
  - name: Install microk8s
    become: yes
    snap:
      name: microk8s
      classic: yes

  - name: Microk8s wait ready
    command: microk8s status --wait-ready

  - name: Enable services
    shell: microk8s enable dashboard dns

  - name: Install helm
    snap:
      name: helm
      classic: yes

  - name: Add remote chart repo
    kubernetes.core.helm_repository:
      name: remote
      repo_url: "https://danielkhan-v1.github.io/lab-k8s/"

  - name: Helm Jenkins start
    kubernetes.core.helm:
      release_name: "jenkins"
      release_namespace: "jenkins"
      create_namespace: yes
      kubeconfig: ~/.kube/config
      chart_ref: remote/jenkins

  - name: Helm Postgres start
    kubernetes.core.helm:
      release_name: "postgres"
      release_namespace: "postgres"
      create_namespace: yes
      kubeconfig: ~/.kube/config
      chart_ref: remote/postgres

  - name: Helm Sonarqube start
    kubernetes.core.helm:
      release_name: "sonarqube"
      release_namespace: "sonarqube"
      create_namespace: yes
      kubeconfig: ~/.kube/config
      chart_ref: remote/sonarqube